### ISSUE TITLE
SQL Injection Vulns

### ISSUE THREAD

**Issue by jcuenod** [just1689/pg-gateway#1]
Just reading some of your code and I noticed that this looks vulnerable.
https://github.com/just1689/pg-gateway/blob/8b9015fd6e57d58f14e2291c4c927493b9e7f4f7/db/query.go#L50

**Comment by just1689** [comment]
Ooh. There's a lot to think about here. Normally I would agree with you. String concatenation from user supplied strings is no way to build a query.

Taking a step back, I've been wondering: What is the responsibility of this application and who is the user? I believe that this a database driver and the user is the programmer. 

If that is the case, then checking for sql injection is out of scope. If it's meant to be public-facing, for browsers to consume & users to call then that introduces a number of other concerns: role-based table access, mutation and possibly resource constraints (rate limiting, query timeout etc), sql injection checks, etc

Would love to hear your thoughts.

**Comment by jcuenod** [comment]
To be honest, I think that security at every layer is the responsibility at that layer.

Drivers seem have string interpolation stuff like "SELECT * FROM users WHERE id=$1" to sanitize stuff going into the query.

At the level of this project, I would say that the comparison to postgrest would lead me to believe that public facing is not necessarily to be avoided. Also, note https://github.com/PostgREST/postgrest/issues/294

**Comment by jcuenod** [comment]
I'm interested in hearing your response...

**Comment by lee-b** [comment]
jcuenod is absolutely correct.  It's called zero trust (and also just not writing buggy, vulnerable code).  You cannot assume that anyone connecting to your API is a valid user (or worse, a valid subset such as "legitimate programmer of this application", whatever that means).  Simply, you are implementing an API contract, and that CONTRACT must be honored.  i.e., it must do what it says, and NO MORE.  So if it takes a variable and uses that as a database field identifier, it MUST NOT allow that variable to be used as a statement, for example.  That -- the SECURE implementation of the API contract -- is the responsibility of the API.

Ticket should be re-opened and not closed until resolved.  As jcuenod says, that could take the form of secure code, or documentation warnings (which should be in big, red letters on the first page) that the API is not fully secure.
